export const CREATE_MINIONS_GROUP_REQUEST = 'CREATE_MINIONS_GROUP_REQUEST';
export const CREATE_MINIONS_GROUP_SUCCESS = 'CREATE_MINIONS_GROUP_SUCCESS';
export const CREATE_MINIONS_GROUP_FAIL = 'CREATE_MINIONS_GROUP_FAIL';