export const EDIT_MINION_GROUPS_REQUEST = 'EDIT_MINION_GROUPS_REQUEST';
export const EDIT_MINION_GROUPS_SUCCESS = 'EDIT_MINION_GROUPS_SUCCESS';
export const EDIT_MINION_GROUPS_FAIL = 'EDIT_MINION_GROUPS_FAIL';