export const EDIT_MINIONS_GROUP_REQUEST = 'EDIT_MINIONS_GROUP_REQUEST';
export const EDIT_MINIONS_GROUP_SUCCESS = 'EDIT_MINIONS_GROUP_SUCCESS';
export const EDIT_MINIONS_GROUP_FAIL = 'EDIT_MINIONS_GROUP_FAIL';