export const GET_GROUPS_BY_MINION_REQUEST = 'GET_GROUPS_BY_MINION_REQUEST';
export const GET_GROUPS_BY_MINION_SUCCESS = 'GET_GROUPS_BY_MINION_SUCCESS';
export const GET_GROUPS_BY_MINION_FAIL = 'GET_GROUPS_BY_MINION_FAIL';