export const GET_GROUPED_MINIONS_REQUEST = 'GET_GROUPED_MINIONS_REQUEST';
export const GET_GROUPED_MINIONS_SUCCESS = 'GET_GROUPED_MINIONS_SUCCESS';
export const GET_GROUPED_MINIONS_FAIL = 'GET_GROUPED_MINIONS_FAIL';