export const COUNTS_STATUS = 'COUNTS_STATUS';
export const COUNTS_GROUP = 'COUNTS_GROUP';
export const ACCEPTED_MINIONS = 'ACCEPTED_MINIONS';
export const DENIED_MINIONS = 'DENIED_MINIONS';
export const REJECTED_MINIONS = 'REJECTED_MINIONS';
export const UNACCEPTED_MINIONS = 'UNACCEPTED_MINIONS';