export const REEXECUTE_SCRIPTS_REQUEST = 'REEXECUTE_SCRIPTS_REQUEST';
export const REEXECUTE_SCRIPTS_SUCCESS = 'REEXECUTE_SCRIPTS_SUCCESS';
export const REEXECUTE_SCRIPTS_FAIL = 'REEXECUTE_SCRIPTS_FAIL';