export const REMOVE_MINIONS_GROUP_REQUEST = 'REMOVE_MINIONS_GROUP_REQUEST';
export const REMOVE_MINIONS_GROUP_SUCCESS = 'REMOVE_MINIONS_GROUP_SUCCESS';
export const REMOVE_MINIONS_GROUP_FAIL = 'REMOVE_MINIONS_GROUP_FAIL';